### ISSUE TITLE
pdf 학습 버튼 ui 만들기

### ISSUE THREAD

**Issue by why-arong** [OOAD-SSamGPT/gpt-plugin-ssam#27]
구체적으로 이 버튼의 이름은 뭐로 할 지 모르겠지만
아무튼 버튼을 누르면 chatpdf가 학습되도록 구현해야 함

**Comment by joonyoung1** [comment]
단순히 파일을 열었을 때 수행하는건 어떨까요?
Auto Learning 등의 옵션을 설정해서 사용자가 이를 선택하도록 하는것도 괜찮을 것 같고,
이 옵션이 꺼져있다면 메뉴바에서 ChatPDF를 준비시키는 항목을 추가해도 괜찮을 것 같아요
되도록 버튼이 적을수록 UI 구성이 깔끔해질 것 같습니다.

 + 명칭은 ChatPDF로 정해진건가요?

**Comment by joonyoung1** [comment]
ChatbotController와 연동되도록 구현했습니다.
다만 PDF가 열려있지 않은 상태에서 요청한다거나, 이미 파일이 열려있는 상태에서 다른 파일을 여는 등
오류가 날만한 상황들은 아직 고려되지 않은 상태입니다.
단순히 이런 API를 사용하면 된다고 생각하시면 될 것 같습니다.

ChatbotController가 생성될 때 PDF를 함께 받습니다.
threading으로 pdf의 내용을 학습시키거나, 번역등을 포함한 가공하는 과정,
실질적인 챗봇 모델등은 다른 클래스로 구현하던, 내부적인 메소드로 포함시키면 될 것 같습니다.

handle_request 메소드에 question으로 사용자가 입력한 질문이 들어오고,
답변은 push_answer(answer) 형태로 사용하시면 되겠습니다.
