### ISSUE TITLE
시작했을 때 load chatbot 눌렀을 때

### ISSUE THREAD

**Issue by why-arong** [OOAD-SSamGPT/gpt-plugin-ssam#34]
pdf 불러오기 전 load chatbot 눌렀을 때
아무 반응이 없는데 에러처리를 해야 할 듯

**Comment by joonyoung1** [comment]
open하기 전에 load chatbot하는 오류를 해결하려고
무시하도록 처리한건데 메세지라도 출력할까요?

**Comment by joonyoung1** [comment]
pdf 로딩 전엔 아예 load chatbot 버튼이 나타나지 않도록 수정
