### ISSUE TITLE
페이지 확대/축소 개발

### ISSUE THREAD

**Issue by joonyoung1** [OOAD-SSamGPT/gpt-plugin-ssam#6]
개발해야할 기능들
- [x] +, - 버튼
- [ ] 단축키
- [x] 직접 scale 값을 입력
- [x] 너비 맞춤, 페이지 맞춤 등의 Scale Policy

**Comment by why-arong** [comment]
라벨 붙이거나 토글 가능합니다

**Comment by why-arong** [comment]
- [ ] +, - 버튼
- [ ] 단축키
- [ ] 직접 scale 값을 입력
- [ ] 너비 맞춤, 페이지 맞춤 등

개발이 되었다는 건지 할거라는 건지 모르겠네요

**Comment by joonyoung1** [comment]
단축키 기능은 나중에 모든 기능들이 정해졌을 때
한 번에 추가하는 편이 나을 것 같습니다.
